"""corrected the uid data type from uuid to str

Revision ID: e938f5defe51
Revises: 9ea21b0b4492
Create Date: 2025-02-25 22:27:36.977871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e938f5defe51'
down_revision: Union[str, None] = '9ea21b0b4492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
